=== brnicot/bdd/vi05/NOTE.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="mesNotes">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="etudiant" minOccurs="0" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="nom" type="xs:string"/>
							<xs:element name="prenom" type="xs:string"/>
							<xs:element name="dateNaissance">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="jour" type="xs:integer"/>
										<xs:element name="mois" type="xs:integer"/>
										<xs:element name="annee" type="xs:integer"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="resultat" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="partiel" type="xs:string"/>
										<xs:element name="note" type="xs:integer"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="idetud" type="xs:token" use="required"/>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
		<xs:key name="cleEtudiant">
			<xs:selector xpath="etudiant"/>
			<xs:field xpath="@idetud"/>
		</xs:key>
	</xs:element>
</xs:schema>

=== brnicot/bdd/vi05/NOTE.xml
<?xml version="1.0"?>
<?xml-stylesheet type="text/xsl" href="Z:\DBJGBY~H\bd\vi05\1.xml"?>
<mesNotes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Z:\DBJGBY~H\bd\vi05\note.xsd">
	<etudiant idetud="E2">
		<nom>Zetofrais</nom>
		<prenom>Melanie</prenom>
		<dateNaissance>
			<jour>03</jour>
			<mois>11</mois>
			<annee>1982</annee>
		</dateNaissance>
		<resultat>
			<partiel>UML</partiel>
			<note>6</note>
		</resultat>
		<resultat>
			<partiel>XML</partiel>
			<note>4</note>
		</resultat>
	</etudiant>
	<etudiant idetud="E1">
		<nom>Zeblouse</nom>
		<prenom>Agathe</prenom>
		<dateNaissance>
			<jour>18</jour>
			<mois>02</mois>
			<annee>1983</annee>
		</dateNaissance>
		<resultat>
			<partiel>UML</partiel>
			<note>8</note>
		</resultat>
		<resultat>
			<partiel>XML</partiel>
			<note>9</note>
		</resultat>
	</etudiant>
	<etudiant idetud="E4">
		<nom>Bricot</nom>
		<prenom>Juda</prenom>
		<dateNaissance>
			<jour>15</jour>
			<mois>03</mois>
			<annee>1982</annee>
		</dateNaissance>
		<resultat>
			<partiel>UML</partiel>
			<note>10</note>
		</resultat>
		<resultat>
			<partiel>XML</partiel>
			<note>1</note>
		</resultat>
		<resultat>
			<partiel>Java</partiel>
			<note>7</note>
		</resultat>
	</etudiant>
	<etudiant idetud="E3">
		<nom>Ouzy</nom>
		<prenom>Jacques</prenom>
		<dateNaissance>
			<jour>01</jour>
			<mois>12</mois>
			<annee>1977</annee>
		</dateNaissance>
		<resultat>
			<partiel>UML</partiel>
			<note>11</note>
		</resultat>
	</etudiant>
	<etudiant idetud="E5">
		<nom>Aimelle</nom>
		<prenom>X</prenom>
		<dateNaissance>
			<jour>11</jour>
			<mois>12</mois>
			<annee>1992</annee>
		</dateNaissance>
		<resultat>
			<partiel>XML</partiel>
			<note>1</note>
		</resultat>
	</etudiant>
</mesNotes>
